#!/usr/bin/env python3
"""
build_augmented_data.py — Prepare the lagged data file and emit run commands.

Creates the augmented CSV that the publication run consumes: each candidate
``base__tK`` becomes a duplicate of its base column. The engine applies the lag
internally via ``--tau-dict``, so the duplicates are identical copies and no
manual shifting occurs. Also emits the exact ``--inputs`` / ``--tau-dict`` and a
ready-to-run command per target, and prints a coverage diagnostic so the valid
date range is confirmed before committing to the long run.

Usage:
    python3 build_augmented_data.py                 # default 2000 surrogates
    python3 build_augmented_data.py --n-cores 8 --n-surrogates 2000

Author: Matthew Rybecky
"""

import argparse
import json
import logging
import sys
from pathlib import Path

import pandas as pd

from pub_config import PublicationConfig, base_of, TAU_DELIM

logging.basicConfig(level=logging.INFO, format='%(levelname)s - %(message)s')
logger = logging.getLogger(__name__)


def build_augmented(cfg: PublicationConfig) -> pd.DataFrame:
    """
    Write the augmented CSV with duplicated ``base__tK`` candidate columns.

    Parameters
    ----------
    cfg : PublicationConfig
        Frozen specification.

    Returns
    -------
    df : pd.DataFrame
        The augmented dataframe (also written to ``cfg.data_file_lagged``).
    """
    base_path = Path(cfg.data_file_base)
    if not base_path.exists():
        raise FileNotFoundError(f"Base data file not found: {base_path}")

    df = pd.read_csv(base_path)
    df[cfg.time_col] = pd.to_datetime(df[cfg.time_col])
    df = df.sort_values(cfg.time_col).reset_index(drop=True)

    missing_sources = [c for c in cfg.source_columns() if c not in df.columns]
    if missing_sources:
        raise KeyError(f"Source columns absent from data: {missing_sources}")
    missing_targets = [t for t in cfg.targets if t not in df.columns]
    if missing_targets:
        raise KeyError(f"Target columns absent from data: {missing_targets}")

    # Each candidate maps to one or more lagged data columns; a vector candidate
    # (e.g. circular wind direction) expands to its component columns. The
    # un-lagged source column is the lagged name with its ``__tK`` suffix removed.
    col_map = cfg.column_map()
    for cols in col_map.values():
        for col in cols:
            src = col.rsplit(TAU_DELIM, 1)[0]
            df[col] = df[src]

    out_path = Path(cfg.data_file_lagged)
    df.to_csv(out_path, index=False)
    logger.info(f"Wrote {out_path} ({len(df)} rows, "
                f"{len(cfg.data_columns())} candidate data columns added)")
    return df


def coverage_report(df: pd.DataFrame, cfg: PublicationConfig) -> None:
    """Print first/last valid timestamp and valid count per base and target."""
    logger.info("Coverage (first/last valid timestamp, n_valid):")
    cols = cfg.source_columns() + cfg.targets
    for col in cols:
        valid = df[[cfg.time_col, col]].dropna()
        if valid.empty:
            logger.info(f"  {col:>16}: NO VALID DATA")
            continue
        first = valid[cfg.time_col].iloc[0].date()
        last = valid[cfg.time_col].iloc[-1].date()
        logger.info(f"  {col:>16}: {first} -> {last}  (n={len(valid)})")


def emit_commands(cfg: PublicationConfig, n_cores: int,
                  n_surrogates: int) -> None:
    """Write publication_run_commands.sh and print the per-target commands."""
    cores_arg = f"--n-cores {n_cores} " if n_cores else ""
    py = sys.executable  # use the same interpreter that generated this file
    vb = cfg.vector_bases()
    vb_arg = (f"  --vector-bases '{json.dumps(vb, separators=(',', ':'))}' \\\n"
              if vb else "")

    lines = ["#!/usr/bin/env bash",
             "set -euo pipefail",
             "# Generated by build_augmented_data.py — publication composite run.",
             ""]
    for target in cfg.targets:
        inputs = " ".join(cfg.candidates(target))
        tau_json = json.dumps(cfg.tau_map(target), separators=(',', ':'))
        cmd = (
            f"{py} TE_Regime_Analysis.py \\\n"
            f"  --target {target} \\\n"
            f"  --inputs {inputs} \\\n"
            f"  --tau-dict '{tau_json}' \\\n"
            f"{vb_arg}"
            f"  --data-file {cfg.data_file_lagged} \\\n"
            f"  --window-days {cfg.window_days} "
            f"--history-length {cfg.history_length} \\\n"
            f"  --n-surrogates {n_surrogates} "
            f"--surrogate-type {cfg.surrogate_type} \\\n"
            f"  {cores_arg}\\\n"
            f"  --output-dir {cfg.output_base}/{target}"
        )
        lines.append(cmd)
        lines.append("")

    script = Path("publication_run_commands.sh")
    script.write_text("\n".join(lines) + "\n")
    script.chmod(0o755)
    logger.info(f"Wrote {script} ({len(cfg.targets)} target commands)")
    print("\n" + "\n".join(lines))


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Build augmented data and emit publication run commands.")
    parser.add_argument('--n-cores', type=int, default=None,
                        help='Cores for the emitted run commands (default: auto)')
    parser.add_argument('--n-surrogates', type=int, default=2000,
                        help='IAAFT surrogates for the emitted commands')
    args = parser.parse_args()

    cfg = PublicationConfig(n_surrogates=args.n_surrogates)
    logger.info(f"Spec: {len(cfg.candidates())} candidates, "
                f"{len(cfg.distinct_base_combos())} distinct-base combos, "
                f"targets={cfg.targets}")
    df = build_augmented(cfg)
    coverage_report(df, cfg)
    emit_commands(cfg, args.n_cores, args.n_surrogates)


if __name__ == '__main__':
    main()
