#!/usr/bin/env python3
"""
pub_table_s1.py — Table S1: the SI driver-interaction composite statistics.

Emits the supporting-information stats table for the four pre-specified
composites of the SI S8 appendix (pairs E, H; triples C, D), both
isotope targets each, entirely from their Stage 2 CSVs
(``pub_stage2.py``, 2000 IAAFT per window at publication settings):
per-composite winter mean and peak joint TE as % of per-window
H(target), the peak date, and the fraction of windows above the
per-window IAAFT 95th percentile. Nothing hand-typed (source-of-truth
rule); statistics use the raw per-window values (no presentation
smoothing) over the truncated winter (before ``pub_config.analysis_end``).
Windows exceeding 100% of target entropy are excluded per the
pre-stated rule and counted in a footnote if any occur.

Outputs (LaTeX ``\\input`` whole; diff on regeneration):
    publication_output/tableS1_composites.tex
    publication_output/tableS1_composites.md   (author preview)

Usage:
    .venv/bin/python3 pub_table_s1.py

Author: Matthew Rybecky
"""

from __future__ import annotations

import logging
from pathlib import Path
from typing import Dict, List

import pandas as pd

from pub_config import PublicationConfig
from pub_labels import tau_of

logging.basicConfig(level=logging.INFO, format='%(levelname)s - %(message)s')
logger = logging.getLogger(__name__)

# The fixed SI S8 selection (author rulings 2026-07-10/11); letters are
# the working identifiers from the composite phase.
COMPOSITES = [
    ('E', 'met_rh__t0+met_temp__t0'),
    ('H', 'met_rh__t0+rad_lw_down__t0'),
    ('C', 'met_wdir__t0+met_wspd__t0+rad_lw_down__t0'),
    ('D', 'isen_225_gph__t0+isen_500_gph__t2+rad_lw_down__t0'),
]
TARGETS = ['d_excess', 'dD']

# TeX-safe short member names (mirrors the figure-legend vocabulary).
TEX_BASE = {
    'met_rh': 'RH', 'met_temp': 'Temp.',
    'met_wdir': 'Wind dir.', 'met_wspd': 'Wind speed',
    'rad_lw_down': 'LW$\\downarrow$',
    'isen_225_gph': 'GPH 225 hPa', 'isen_500_gph': 'GPH 500 hPa',
}
TARGET_TEX = {'d_excess': 'd-excess', 'dD': '$\\delta$D'}
TARGET_MD = {'d_excess': 'd-excess', 'dD': 'dD'}


def tex_entity(entity: str) -> str:
    """TeX label for a '+'-joined entity, taus attached."""
    parts = []
    for p in entity.split('+'):
        base = p.rsplit('__t', 1)[0]
        parts.append(f"{TEX_BASE[base]} ($\\tau{{=}}{tau_of(p)}$)")
    return ' + '.join(parts)


def md_entity(entity: str) -> str:
    """Markdown-preview label (no TeX markup)."""
    return (tex_entity(entity)
            .replace('$\\downarrow$', 'v').replace('$\\tau{=}', 'tau=')
            .replace('$', ''))


def composite_stats(base: Path, end: pd.Timestamp, target: str,
                    entity: str) -> Dict:
    """Raw per-window statistics for one composite on one target."""
    path = base / 'stage2' / target / f'stage2_{entity}.csv'
    df = pd.read_csv(path, parse_dates=['timestamp'])
    df = df[df['timestamp'] < end]
    over = int((df['pct_h'] > 100.0).sum())
    df = df[df['pct_h'] <= 100.0]
    peak_row = df.loc[df['pct_h'].idxmax()]
    return {
        'mean': df['pct_h'].mean(),
        'peak': peak_row['pct_h'],
        'peak_date': peak_row['timestamp'],
        'n_sig': int(df['sig95'].sum()),
        'n': len(df),
        'n_over': over,
    }


def gather(base: Path, end: pd.Timestamp) -> List[Dict]:
    """All rows: composites x targets, in appendix order."""
    rows = []
    for letter, entity in COMPOSITES:
        for target in TARGETS:
            s = composite_stats(base, end, target, entity)
            rows.append({'letter': letter, 'entity': entity,
                         'target': target, **s})
    return rows


def build_latex(rows: List[Dict]) -> str:
    """The complete LaTeX table environment."""
    n_over = sum(r['n_over'] for r in rows)
    lines = [
        '% Generated by TE_V1.0.0/pub_table_s1.py from the Stage 2 CSVs.',
        '% Never hand-edit: rerun the script and diff.',
        '\\begin{table}',
        '\\caption{Pre-specified composites of the driver-interaction '
        'appendix: winter mean and peak joint transfer entropy as a '
        'percentage of per-window target entropy, and the fraction of '
        'windows above the per-window IAAFT 95th percentile.$^{a}$}',
        '\\label{tab:si_composites}',
        '\\centering',
        '\\begin{tabular}{l l c c c c}',
        '\\hline',
        'Composite & Target & Mean (\\% of $H$) & Peak (\\% of $H$) & '
        'Peak date & Significant windows \\\\',
        '\\hline',
    ]
    prev = None
    for r in rows:
        label = tex_entity(r['entity']) if r['letter'] != prev else ''
        prev = r['letter']
        lines.append(
            f"{label} & {TARGET_TEX[r['target']]} & {r['mean']:.1f} & "
            f"{r['peak']:.1f} & {r['peak_date']:%b %d} & "
            f"{r['n_sig']}/{r['n']} \\\\")
    lines.append('\\hline')
    foot = ('$^{a}$ Statistics over the truncated winter (window centers '
            'before May 1); 30-day rolling windows; significance from '
            '2000 source-only IAAFT surrogates per window.')
    if n_over:
        foot += (f' {n_over} window(s) exceeding 100\\% of target entropy '
                 'excluded per the pre-stated rule.')
    lines.append(f'\\multicolumn{{6}}{{l}}{{\\footnotesize {foot}}} \\\\')
    lines += ['\\end{tabular}', '\\end{table}']
    return '\n'.join(lines) + '\n'


def build_markdown(rows: List[Dict]) -> str:
    """Author-preview mirror of the LaTeX table."""
    lines = ['# Table S1 preview — composite statistics (from Stage 2 CSVs)',
             '', '| Composite | Target | Mean (% of H) | Peak (% of H) | '
             'Peak date | Significant windows |',
             '| --- | --- | --- | --- | --- | --- |']
    prev = None
    for r in rows:
        label = (f"{r['letter']}: {md_entity(r['entity'])}"
                 if r['letter'] != prev else '')
        prev = r['letter']
        lines.append(
            f"| {label} | {TARGET_MD[r['target']]} | {r['mean']:.1f} | "
            f"{r['peak']:.1f} | {r['peak_date']:%b %d} | "
            f"{r['n_sig']}/{r['n']} |")
    return '\n'.join(lines) + '\n'


def main() -> None:
    cfg = PublicationConfig()
    base = Path(cfg.output_base)
    rows = gather(base, pd.Timestamp(cfg.analysis_end))
    tex = base / 'tableS1_composites.tex'
    md = base / 'tableS1_composites.md'
    tex.write_text(build_latex(rows))
    md.write_text(build_markdown(rows))
    logger.info(f"{len(rows)} rows ({len(COMPOSITES)} composites x "
                f"{len(TARGETS)} targets)")
    logger.info(f"wrote {tex}")
    logger.info(f"wrote {md}")


if __name__ == '__main__':
    main()
