#!/usr/bin/env python3
"""
pub_table1.py — Table 1: the analyzed variable set, from the frozen spec.

Emits the manuscript's variable-specification table entirely from
``pub_config.py``: the 16 base input variables in their four candidate
groups with allowed lags (tau sets, 6-hour steps), the two targets, and
a footnote for the circular wind representation.

Author rulings (2026-07-08): clear descriptive labels only — no code
names, and no instrument/height/native-resolution metadata. A source
attribution column names each data stream at campaign level (SAIL/ARM,
SOS, ERA5, SAIL-ISO; wording from thesis ch3 — formal data-product
citations join when bibliography item B5 lands). dD and d-excess are the
only targets (H2O_ppm is out of scope). CO2 tower variables are molar
densities, not fluxes; GPH levels are pressure levels (hPa).

Outputs (LaTeX ``\\input`` whole; diff on regeneration; plain ``\\hline``
rules so no package dependency):
    publication_output/table1_variables.tex
    publication_output/table1_variables.md   (author preview)

Usage:
    .venv/bin/python3 pub_table1.py

Author: Matthew Rybecky
"""

from __future__ import annotations

import logging
from pathlib import Path
from typing import List, Tuple

from pub_config import GROUPS, VECTOR_BASES

logging.basicConfig(level=logging.INFO, format='%(levelname)s - %(message)s')
logger = logging.getLogger(__name__)

OUT_DIR = Path('publication_output')

# Targets (H2O_ppm is out of scope; dD and d-excess only).
MAIN_TARGETS = ['dD', 'd_excess']

# Section titles, parallel to pub_config.GROUPS (asserted below).
GROUP_TITLES = [
    'Local thermodynamic and radiative state',
    'Wind and transport',
    'Eddy-covariance tower',
    'Far-field advection (ERA5)',
]

# Clear labels, LaTeX-safe (markers reference the footnotes below).
TEX_LABELS = {
    'met_temp': 'Air temperature',
    'met_rh': 'Relative humidity',
    'rad_sw_down': 'Downwelling shortwave radiation',
    'rad_lw_down': 'Downwelling longwave radiation',
    'rad_lw_up': 'Upwelling longwave radiation',
    'rad_net': 'Net radiation',
    'met_wspd': 'Wind speed',
    'met_wdir': 'Wind direction$^{b}$',
    'flux_3m_h2o': 'Water vapor flux, 3 m',
    'flux_10m_h2o': 'Water vapor flux, 10 m',
    'flux_20m_h2o': 'Water vapor flux, 20 m',
    'flux_3m_co2_density': 'CO$_2$ density, 3 m',
    'flux_10m_co2_density': 'CO$_2$ density, 10 m',
    'flux_20m_co2_density': 'CO$_2$ density, 20 m',
    'isen_225_gph': 'Geopotential height, 225 hPa',
    'isen_500_gph': 'Geopotential height, 500 hPa',
}
TARGET_TEX = {'dD': '$\\delta$D', 'd_excess': 'd-excess'}

# Source attribution per data stream (campaign level; thesis ch3 wording).
# Formal data-product citations enter with bibliography item B5.
SOURCES = {
    'met_temp': 'SAIL (ARM surface meteorology)',
    'met_rh': 'SAIL (ARM surface meteorology)',
    'met_wspd': 'SAIL (ARM surface meteorology)',
    'met_wdir': 'SAIL (ARM surface meteorology)',
    'rad_sw_down': 'SAIL (ARM radiation)',
    'rad_lw_down': 'SAIL (ARM radiation)',
    'rad_lw_up': 'SAIL (ARM radiation)',
    'rad_net': 'SAIL (ARM radiation)',
    'flux_3m_h2o': 'SOS flux tower',
    'flux_10m_h2o': 'SOS flux tower',
    'flux_20m_h2o': 'SOS flux tower',
    'flux_3m_co2_density': 'SOS flux tower',
    'flux_10m_co2_density': 'SOS flux tower',
    'flux_20m_co2_density': 'SOS flux tower',
    'isen_225_gph': 'ERA5 reanalysis',
    'isen_500_gph': 'ERA5 reanalysis',
}
TARGET_SOURCES = {
    'dD': 'SAIL-ISO (UNM guest instrument)',
    'd_excess': 'SAIL-ISO (UNM guest instrument)',
}

# Markdown-preview variants (no TeX markup).
MD_LABELS = {k: v.replace('$_2$', '2').replace('$^{b}$', ' (b)')
             for k, v in TEX_LABELS.items()}
MD_TARGETS = {'dD': 'dD', 'd_excess': 'd-excess'}


def spec_rows() -> List[Tuple[str, List[Tuple[str, str]]]]:
    """(section title, [(base, lag string), ...]) from the frozen spec."""
    assert len(GROUP_TITLES) == len(GROUPS), \
        'GROUP_TITLES out of step with pub_config.GROUPS'
    sections = []
    for title, (bases, taus) in zip(GROUP_TITLES, GROUPS):
        lag_text = ', '.join(str(t) for t in taus)
        sections.append((title, [(b, lag_text) for b in bases]))
    return sections


def footnotes() -> List[Tuple[str, str]]:
    """Footnote letters and their text, from the spec where derivable."""
    wind_components = ', '.join(VECTOR_BASES['met_wdir'])
    return [
        ('a', 'Allowed lags $\\tau$ in 6-hour steps ($\\tau=1$ is 6 h).'),
        ('b', f'Wind direction enters as circular components '
              f'({wind_components}), a single two-column input.'),
    ]


def build_latex() -> str:
    """The complete LaTeX table environment."""
    lines = [
        '% Generated by TE_V1.0.0/pub_table1.py from pub_config.py.',
        '% Never hand-edit: rerun the script and diff.',
        '\\begin{table}',
        '\\caption{Analyzed variables: the four candidate input groups '
        'with their allowed lags, and the two targets.}',
        '\\label{tab:variables}',
        '\\centering',
        '\\begin{tabular}{l l c}',
        '\\hline',
        'Variable & Source & Allowed lags $\\tau$ (6-h steps)$^{a}$ \\\\',
        '\\hline',
    ]
    for title, rows in spec_rows():
        lines.append(f'\\multicolumn{{3}}{{l}}{{\\textit{{{title}}}}} \\\\')
        for base, lag_text in rows:
            lines.append(f'\\quad {TEX_LABELS[base]} & {SOURCES[base]} '
                         f'& {lag_text} \\\\')
    lines.append('\\multicolumn{3}{l}{\\textit{Targets (never inputs)}} \\\\')
    for tgt in MAIN_TARGETS:
        lines.append(f'\\quad {TARGET_TEX[tgt]} & {TARGET_SOURCES[tgt]} '
                     f'& --- \\\\')
    lines.append('\\hline')
    for letter, text in footnotes():
        lines.append(f'\\multicolumn{{3}}{{l}}{{\\footnotesize '
                     f'$^{{{letter}}}$ {text}}} \\\\')
    lines += ['\\end{tabular}', '\\end{table}']
    return '\n'.join(lines) + '\n'


def build_markdown() -> str:
    """Author-preview mirror of the LaTeX table."""
    lines = ['# Table 1 preview — analyzed variables (from pub_config.py)',
             '', '| Variable | Source | Allowed lags τ (6-h steps) (a) |',
             '| --- | --- | --- |']
    for title, rows in spec_rows():
        lines.append(f'| **{title}** | | |')
        for base, lag_text in rows:
            lines.append(f'| {MD_LABELS[base]} | {SOURCES[base]} '
                         f'| {lag_text} |')
    lines.append('| **Targets (never inputs)** | | |')
    for tgt in MAIN_TARGETS:
        lines.append(f'| {MD_TARGETS[tgt]} | {TARGET_SOURCES[tgt]} | — |')
    lines.append('')
    for letter, text in footnotes():
        clean = (text.replace('$\\tau$', 'tau').replace('$\\tau=1$', 'tau=1')
                 .replace('H$_2$O', 'H2O').replace('--', '-'))
        lines.append(f'({letter}) {clean}')
    return '\n'.join(lines) + '\n'


def main() -> None:
    OUT_DIR.mkdir(exist_ok=True)
    n_bases = sum(len(rows) for _, rows in spec_rows())
    tex = OUT_DIR / 'table1_variables.tex'
    md = OUT_DIR / 'table1_variables.md'
    tex.write_text(build_latex())
    md.write_text(build_markdown())
    logger.info(f"{n_bases} input variables + {len(MAIN_TARGETS)} targets")
    logger.info(f"wrote {tex}")
    logger.info(f"wrote {md}")


if __name__ == '__main__':
    main()
